[workspace]

members = [
    "compiler/kona",

    # Basic passes:
    "compiler/kona_source",
    "compiler/kona_diagnostic",
    "compiler/kona_parse",
    "compiler/kona_ast",
    "compiler/kona_type_ir",
    "compiler/kona_eval",

    # Utilities:
    "compiler/kona_memory",
]
