[package]
name = "kona_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
kona_source = { path = "../kona_source" }
kona_ast = { path = "../kona_ast" }
kona_memory = { path = "../kona_memory" }
kona_diagnostic = { path = "../kona_diagnostic" }
lazy_static = "1.4.0"
